apiVersion: v1
kind: Secret
metadata:
  name: aws-example
  annotations:
    avp.kubernetes.io/path: "dev/app" # The name of your AWS Secret
stringData:
  username: <username>
  password: <password>
type: Opaque
